import { JwtType } from '@securustablets/libraries.httpsecurity';
import { _ } from '@securustablets/libraries.utils';
import { SecurityFactory } from '@securustablets/libraries.utils-test';
import { expect } from 'chai';
import * as request from 'supertest';
import {
  IntervalUnit,
  Product,
  ProductStatus,
} from '../../../src/controllers/models/Product';
import { ProductManager } from '../../../src/lib/ProductManager';
import { ProductTypeManager } from '../../../src/lib/ProductTypeManager';
import { app } from '../../../src/main';
import { ModelFactory } from '../../utils/ModelFactory';
import * as client from '../../utils/client';
import { IntegrationTestSuite } from '../IntegrationTestSuite';
import '../global.spec';

describe('TestController', function () {
  IntegrationTestSuite.setUp(this);
  let corpJwt: string;
  beforeEach(async () => {
    corpJwt = await SecurityFactory.jwt(
      SecurityFactory.corpJwt({
        jwtType: JwtType.Corporate,
        username: 'testUser',
        permissions: ['catalogAdmin'],
      }),
    );
  });
  describe('bulk', () => {
    const productManager = new ProductManager();

    it('should insert data', async () => {
      await client.bulk(bulkData());

      const testData = _.sortBy(bulkDataFlat(), 'meta.name');
      const resultData = _.sortBy(await productManager.find(), 'meta.name');

      expect(resultData.length).to.equal(testData.length);

      for (let i = 0; i < testData.length; i++) {
        expect(
          _.omit(
            resultData[i],
            'productId',
            'childProductIds',
            'childProducts',
            'cdate',
            'udate',
            'version',
            'available',
            'subscribable',
            'isBlocked',
          ),
        ).to.deep.equal(
          _.omit(
            testData[i],
            'productId',
            'childProductIds',
            'childProducts',
            'cdate',
            'udate',
            'version',
            'available',
            'subscribable',
            'purchaseOptions',
            'cache',
          ),
        );

        if (!_.isUndefined(testData[i].childProductIds)) {
          expect(testData[i].childProductIds.length).to.equal(
            resultData[i].childProductIds.length,
          );
          const resolvedResultData =
            await productManager.findOneByProductIdOrFail(
              resultData[i].productId,
              true,
            );
          expect(
            _.map(testData[i].childProducts, 'meta.name').sort(),
          ).to.deep.equal(
            _.map(resolvedResultData.childProducts, 'meta.name').sort(),
          );
        }
      }
    });
    it('should do nothing if no data is sent', async () => {
      await client.bulk([]);

      expect((await productManager.find()).length).to.equal(0);
    });
  });
  describe('wipe', () => {
    it('should wipe data', async () => {
      const productTypeMan = new ProductTypeManager();
      const productSchema = await productTypeMan.getProductType('movie');

      await request(app)
        .post(`/products`)
        .set('X-API-KEY', 'API_KEY_DEV')
        .send(ModelFactory.productFromSchema(productSchema.jsonSchema))
        .expect(200);

      await request(app).post('/test/wipe').expect(204);

      const { body } = await request(app)
        .post(`/products/search`)
        .set('Authorization', `Bearer ${corpJwt}`)
        .expect(200);

      expect(body.data).to.have.lengthOf(0);
    });
  });

  function bulkDataFlat(): Product[] {
    const flattenProduct = (product) =>
      _.flatMapDeep(product.childProducts, flattenProduct).concat(product);

    return _.flatMapDeep(bulkData(), flattenProduct);
  }

  function bulkData(): Product[] {
    return [
      {
        meta: {
          thumbnail: '',
          demo: false,
          name: 'Ardoc Subscriber',
          type: 'personal',
          premiumContent: false,
          basePrice: {
            subscription: 14.99,
          },
          description:
            'It???s the SecureView Tablet you love, now with more Apps!',
          billingInterval: {
            count: 1,
            interval: IntervalUnit.Months,
          },
        },
        filter: {
          sType: 'st',
          channel: ['inmateMakeMine', 'OrderingService', 'securusTablet'],
          customerId: ['I-003320'],
        },
        source: {
          vendorName: 'securus3',
          vendorProductId: 'ardocSubscriber',
          productTypeId: 'tabletPackage',
        },
        status: ProductStatus.Active,
        productId: 2634,
        purchaseCode: 'TABLET',
        productTypeId: 'tabletPackage',
        productTypeGroupId: 'tabletPackage',
        fulfillmentType: 'physical',
        purchaseTypes: ['subscription'],
        childProductIds: [
          2519, 2521, 2522, 2529, 2531, 2532, 2534, 2538, 2539, 2544, 2545,
          2547, 2551, 2552, 2555, 2559, 2560, 2561, 2563, 2565, 2568, 2569,
          2570, 2577, 2580, 2584, 2585, 2588, 2589, 2590, 2593, 2595, 2598,
          2600, 2605, 2606,
        ],
        cdate: '2020-09-22T16:33:37.587Z',
        udate: '2020-09-22T16:33:37.599Z',
        version: 1,
        available: false,
        purchaseOptions: [
          {
            type: 'subscription',
            totalPrice: 14.99,
            priceDetails: [
              {
                name: 'Price',
                amount: 14.99,
                type: 'price',
              },
            ],
          },
        ],
        cache: false,
        childProducts: [
          {
            meta: {
              name: 'Lexis',
              category: 'education',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              androidClass: 'com.securus.lexis',
              privilegedApp: false,
              cameraRequired: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2519,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.043Z',
            udate: '2020-09-22T16:33:36.056Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Media Store',
              category: 'media',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              description: 'Purchase premium media',
              androidClass: 'net.securustech.sv.mediastore',
              privilegedApp: false,
              cameraRequired: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2521,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.046Z',
            udate: '2020-09-22T16:33:36.065Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'TiltMazes',
              category: 'games',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              androidClass: 'com.lecz.android.tiltmazes',
              privilegedApp: false,
              cameraRequired: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2522,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.062Z',
            udate: '2020-09-22T16:33:36.075Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'EBook Reader',
              category: 'media',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              androidClass: 'net.securustech.sv.ebookreader',
              privilegedApp: false,
              cameraRequired: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2529,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.115Z',
            udate: '2020-09-22T16:33:36.126Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Videograms',
              category: 'message',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              androidClass: 'com.jpay.videograms.sv',
              privilegedApp: false,
              cameraRequired: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2531,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.122Z',
            udate: '2020-09-22T16:33:36.131Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'ECard',
              category: 'message',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              androidClass: 'com.jpay.ecard.sv',
              privilegedApp: false,
              cameraRequired: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2532,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.130Z',
            udate: '2020-09-22T16:33:36.139Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'EMail',
              category: 'message',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              androidClass: 'com.jpay.email.sv',
              privilegedApp: false,
              cameraRequired: false,
              postInstallCommand:
                'rm -rf /sdcard/mail/Inbox.xml /sdcard/mail/Sent.xml /sdcard/mail/KioskInfo.xml /sdcard/mail/KioskXInfo.xml',
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2534,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.147Z',
            udate: '2020-09-22T16:33:36.165Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Agreements',
              category: 'system',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: true,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.agreements',
              privilegedApp: false,
              appManagementAllowed: false,
            },
            status: 'Active',
            productId: 2538,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.207Z',
            udate: '2020-09-22T16:33:36.218Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'MyAccount',
              category: 'support',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.myaccount',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2539,

            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.207Z',
            udate: '2020-09-22T16:33:36.220Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'SecureJobs',
              category: 'media',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.cac.jobview',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2544,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.242Z',
            udate: '2020-09-22T16:33:36.250Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'MakeMine',
              category: 'system',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              description:
                'Inmates can Order a subscription using their debit account or fulfill an existing F&F order with a FT',
              androidClass: 'net.securustech.sv.makemine',
              privilegedApp: false,
              appManagementAllowed: false,
            },
            status: 'Active',
            productId: 2545,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.244Z',
            udate: '2020-09-22T16:33:36.260Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Mobi Office',
              category: 'education',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'com.mobisystems.editor.jpay',
              privilegedApp: false,
              postInstallCommand:
                'mkdir -p $EXTERNAL_STORAGE/mobioffice; mkdir -p $EXTERNAL_STORAGE/Android/data/com.jpay.lantern; ' +
                'echo $EXTERNAL_STORAGE/mobioffice > $EXTERNAL_STORAGE/Android/data/com.jpay.lantern/mydocs_path_source.txt',
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2547,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.258Z',
            udate: '2020-09-22T16:33:36.266Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Sudoku',
              category: 'games',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'com.jpay.sudoku',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2551,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.286Z',
            udate: '2020-09-22T16:33:36.295Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'XOXOXO',
              category: 'games',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'com.anpeco.xoxoxo',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2552,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.289Z',
            udate: '2020-09-22T16:33:36.299Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Inmate Forms',
              category: 'message',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.inmateforms',
              privilegedApp: false,
              appManagementAllowed: false,
            },
            status: 'Active',
            productId: 2555,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.316Z',
            udate: '2020-09-22T16:33:36.323Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Lexis Nexis',
              category: 'education',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.cac.lexisnexis',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2559,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.344Z',
            udate: '2020-09-22T16:33:36.357Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Stewart',
              category: 'commissary',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              description: 'Stewart commissary app',
              androidClass: 'net.securustech.sv.cac.stewart',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2560,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.344Z',
            udate: '2020-09-22T16:33:36.359Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Chasing the Dragon Video App',
              category: 'games',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.ctdlocal',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2561,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.347Z',
            udate: '2020-09-22T16:33:36.358Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Media Provider',
              category: 'media',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              description: 'library to support media player',
              androidClass: 'com.android.providers.media',
              privilegedApp: true,
              appManagementAllowed: false,
            },
            status: 'Active',
            productId: 2563,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.367Z',
            udate: '2020-09-22T16:33:36.377Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Fast Case',
              category: 'law',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.cac.fastcase',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2565,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.382Z',
            udate: '2020-09-22T16:33:36.390Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Digital Mail Center',
              category: 'message',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.cac.dmc',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2568,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.400Z',
            udate: '2020-09-22T16:33:36.409Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Calculator',
              category: 'utility',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'com.google.android.calculator',
              privilegedApp: false,
              appManagementAllowed: false,
            },
            status: 'Active',
            productId: 2569,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.411Z',
            udate: '2020-09-22T16:33:36.421Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Subscriber',
              category: 'system',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: true,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.subscriber',
              privilegedApp: false,
              appManagementAllowed: false,
            },
            status: 'Active',
            productId: 2570,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.413Z',
            udate: '2020-09-22T16:33:36.424Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Aramark',
              category: 'education',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.aramark',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2577,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.446Z',
            udate: '2020-09-22T16:33:36.457Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Music Player',
              category: 'media',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              description: 'Play music purchased from the JPay media store',
              androidClass: 'net.securustech.sv.music',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2580,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.470Z',
            udate: '2020-09-22T16:33:36.481Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Radio',
              category: 'media',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.radio',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2584,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.503Z',
            udate: '2020-09-22T16:33:36.524Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Kalite',
              category: 'education',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.kalite',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2585,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.504Z',
            udate: '2020-09-22T16:33:36.521Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Ashland',
              category: 'education',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.ashland',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2588,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.539Z',
            udate: '2020-09-22T16:33:36.555Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Secure Law',
              category: 'law',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.SecureLaw',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2589,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.552Z',
            udate: '2020-09-22T16:33:36.561Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'SecureServices',
              category: 'message',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.SecureServices',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2590,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.558Z',
            udate: '2020-09-22T16:33:36.570Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Edovo',
              category: 'law',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'org.chromium.content_shell_apk',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2593,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.574Z',
            udate: '2020-09-22T16:33:36.582Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'The Good Grid',
              category: 'education',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.cac.goodgrid',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2595,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.591Z',
            udate: '2020-09-22T16:33:36.602Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Clock',
              category: 'system',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'net.securustech.sv.deskclock',
              privilegedApp: false,
              appManagementAllowed: false,
            },
            status: 'Active',
            productId: 2598,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.605Z',
            udate: '2020-09-22T16:33:36.616Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'EMessaging',
              category: 'message',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              cameraRequired: false,
              systemApp: false,
              androidClass: 'net.securustech.sv.emessaging',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2600,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.618Z',
            udate: '2020-09-22T16:33:36.627Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              name: 'Chomping Chaz',
              category: 'games',
              compatibility: [],
              basePrice: {
                purchase: 0,
              },
              systemApp: false,
              cameraRequired: false,
              androidClass: 'com.jpay.chompingchaz',
              privilegedApp: false,
              appManagementAllowed: true,
            },
            status: 'Active',
            productId: 2605,
            productTypeId: 'apk',
            productTypeGroupId: 'apk',
            fulfillmentType: 'digital',
            purchaseCode: 'APK',
            purchaseTypes: ['purchase'],
            cdate: '2020-09-22T16:33:36.647Z',
            udate: '2020-09-22T16:33:36.655Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
          },
          {
            meta: {
              sku: '9999-999-9999',
              name: 'JP6 Tablet',
              features: {
                camera: false,
              },
              description: 'JP6 7 Inch Tablet',
              modelNumber: 'jp6',
            },
            source: {
              vendorName: 'securus2',
              vendorProductId: 'mt8163',
              productTypeId: 'device',
            },
            status: 'Active',
            productId: 2606,
            productTypeId: 'device',
            productTypeGroupId: 'device',
            purchaseCode: 'TABLETDEVICE',
            purchaseTypes: ['purchase'],
            childProductIds: [2518, 2541, 2548, 2549, 2556],
            fulfillmentType: 'physical',
            cdate: '2020-09-22T16:33:36.665Z',
            udate: '2020-09-22T16:33:36.670Z',
            version: 1,
            available: false,
            purchaseOptions: [],
            cache: false,
            childProducts: [
              {
                meta: {
                  name: 'svControl',
                  category: 'system',
                  compatibility: [],
                  basePrice: {
                    purchase: 0,
                  },
                  systemApp: true,
                  cameraRequired: false,
                  androidClass: 'net.securustech.sv.svcontrol',
                  privilegedApp: false,
                  appManagementAllowed: false,
                },
                status: 'Active',
                productId: 2518,
                productTypeId: 'apk',
                productTypeGroupId: 'apk',
                fulfillmentType: 'digital',
                purchaseCode: 'APK',
                purchaseTypes: ['purchase'],
                cdate: '2020-09-22T16:33:36.035Z',
                udate: '2020-09-22T16:33:36.053Z',
                version: 1,
                available: false,
                purchaseOptions: [],
                cache: false,
              },
              {
                meta: {
                  name: 'Securus Launcher',
                  category: 'system',
                  compatibility: [],
                  basePrice: {
                    purchase: 0,
                  },
                  systemApp: true,
                  cameraRequired: false,
                  androidClass: 'net.securustech.sv.launcher',
                  privilegedApp: true,
                  postInstallCommand:
                    'mount -o remount,rw /system && rm -rf /system/priv-app/Trebuchet /system/app/Launcher3',
                  appManagementAllowed: false,
                },
                status: 'Active',
                productId: 2541,
                productTypeId: 'apk',
                productTypeGroupId: 'apk',
                fulfillmentType: 'digital',
                purchaseCode: 'APK',
                purchaseTypes: ['purchase'],
                cdate: '2020-09-22T16:33:36.222Z',
                udate: '2020-09-22T16:33:36.231Z',
                version: 1,
                available: false,
                purchaseOptions: [],
                cache: false,
              },
              {
                meta: {
                  name: 'tabletlogging',
                  category: 'system',
                  compatibility: [],
                  basePrice: {
                    purchase: 0,
                  },
                  systemApp: true,
                  cameraRequired: false,
                  description: 'Logs system activity',
                  androidClass: 'net.securustech.sv.tabletlogging',
                  privilegedApp: false,
                  postInstallCommand:
                    'pm grant net.securustech.sv.tabletlogging android.permission.PACKAGE_USAGE_STATS; ' +
                    'am startservice net.securustech.sv.tabletlogging/.receiver.BroadcastService || am startforegroundservice ' +
                    'net.securustech.sv.tabletlogging/.receiver.BroadcastService',
                  appManagementAllowed: true,
                },
                status: 'Active',
                productId: 2548,
                productTypeId: 'apk',
                productTypeGroupId: 'apk',
                fulfillmentType: 'digital',
                purchaseCode: 'APK',
                purchaseTypes: ['purchase'],
                cdate: '2020-09-22T16:33:36.273Z',
                udate: '2020-09-22T16:33:36.281Z',
                version: 1,
                available: false,
                purchaseOptions: [],
                cache: false,
              },
              {
                meta: {
                  name: 'lockscreen',
                  category: 'system',
                  compatibility: [],
                  basePrice: {
                    purchase: 0,
                  },
                  systemApp: true,
                  cameraRequired: false,
                  description:
                    'Increases security by allowing inmates to use the tablet only with correct ID and PIN ',
                  androidClass: 'net.securustech.sv.lockscreen',
                  privilegedApp: false,
                  postInstallCommand:
                    'am startservice net.securustech.sv.lockscreen/.receivers.ScreenService || am start' +
                    '-foreground-service net.securustech.sv.lockscreen/.receivers.ScreenService; if pm list packages | grep' +
                    ' -q org.linphone; then pm disable org.linphone; else log "phone app does not exist"; fi; if [ ! -f ' +
                    '/data/data/dpm_done ];then log "Setting device owner and deleting swipe screen" && dpm set-device-owner' +
                    ' net.securustech.sv.lockscreen/.receivers.MyDeviceAdminReceiver && touch /data/data/dpm_done && sqlite3' +
                    ' /data/system/locksettings.db "UPDATE locksettings SET value = 1 WHERE name = \\"lockscreen.disabled\\""' +
                    ' && log "lockscreen set as device owner, swipe screen deleted"; else log "device owner already exists, delete' +
                    ' swipe screen failed"; fi',
                  appManagementAllowed: false,
                },
                status: 'Active',
                productId: 2549,
                productTypeId: 'apk',
                productTypeGroupId: 'apk',
                fulfillmentType: 'digital',
                purchaseCode: 'APK',
                purchaseTypes: ['purchase'],
                cdate: '2020-09-22T16:33:36.273Z',
                udate: '2020-09-22T16:33:36.285Z',
                version: 1,
                available: false,
                purchaseOptions: [],
                cache: false,
              },
              {
                meta: {
                  name: 'Tablet Info Widget',
                  category: 'system',
                  compatibility: [],
                  basePrice: {
                    purchase: 0,
                  },
                  systemApp: true,
                  cameraRequired: false,
                  androidClass: 'net.securustech.sv.tabletinfo',
                  privilegedApp: false,
                  appManagementAllowed: false,
                },
                status: 'Active',
                productId: 2556,
                productTypeId: 'apk',
                productTypeGroupId: 'apk',
                fulfillmentType: 'digital',
                purchaseCode: 'APK',
                purchaseTypes: ['purchase'],
                cdate: '2020-09-22T16:33:36.317Z',
                udate: '2020-09-22T16:33:36.328Z',
                version: 1,
                available: false,
                purchaseOptions: [],
                cache: false,
              },
            ],
          },
        ],
        subscribable: false,
      },
    ];
  }
});
